### Section 5 Homework

1. What does Pandas stand for?
2. What are the 2 collections used in Pandas?
3. Name 4 things Pandas can do for us.
4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
5. What is a CSV?
6. When cleaning data what values do we not like in our data?


In [6]:
# Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()
import numpy as np
array1 = np.array ([2, 3, 2])
array1.reshape (1, 3)
print(array1)


[2 3 2]


In [9]:
# Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 
array = np.linspace(0, 20, 6)

print(array)

[ 0.  4.  8. 12. 16. 20.]


In [11]:
# Make a Deep Copy of the above array
import copy
array = np.linspace(0, 20, 6)
print(array)

arrayb = copy.deepcopy(array)
print(arrayb)

[ 0.  4.  8. 12. 16. 20.]
[ 0.  4.  8. 12. 16. 20.]


In [12]:
# Concatenate these 3 arrays into a new array named 'newArray'...
#([[25, 16]])
#     ([[11, 2], [13, 4]])
#    ([[7, 81], [5, 6], [11, 12]])
array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array ([[7, 81], [5, 6], [11, 12]])
newarray = np.concatenate((array1, array2, array3), axis = 0)
#is the axis always 0?
print(newarray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [15]:
# Sort 'newArray' in order into 'sortedArray'
sortedArray = np.sort(newarray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [ ]:
# Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.


In [16]:
# Combined and sort the following arrays into one called 'comboArray' 
# one = ([10, 11, 12, 13, 14, 15, 16, 17])
# two = ([20, 21, 22, 23, 24, 25, 26, 27])
# three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
four= np.concatenate((one, two, three), axis = 0)

comboArray = np.sort(four)
print(comboArray)


[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [61]:
# Take 'comboArray' and perform the following slicing activities:

# print sec1 - the 2nd element
print(comboArray [1])

#print sec2 - all elements from the 3rd element to the last
print(comboArray[3:])

# print sec3 - all elements from the 4th to the 14th elements
print(comboArray[4:15])

# print sec4 - the last 6 elements
print(comboArray[-6:])

# print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print(comboArray[:-8])

# print sec6 - from #20 every even element to the end
print(comboArray[:21:2])

# print sec7 - from the last element moving forward, every 5th element.
print(comboArray[-1::5])
#not sure why this isn't working?


1
[ 3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 4  5  6  7 10 11 12 13 14 15 16]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17]
[ 0  2  4  6 10 12 14 16 20 22 24]
[]


In [64]:
# Using Series, create a DataFrame that looks like this:

import pandas as pd

Ingredients = pd.Series(["Flour","Milk","Eggs","Spam"])
Quantity = pd.Series([4, 1, 2, 1])
Unit = pd.Series(["cups","cup","large","can"])
print(Ingredients)
print(Quantity)
print(Unit)

df = pd.concat([Ingredients, Quantity, Unit ], axis=1)
print(df)

Ingredients = pd.Series(["Flour","Milk","Eggs","Spam"], name='Ingredients')
Quantity = pd.Series([4, 1, 2, 1], name='Quantity')
Unit  = pd.Series(["cups","cup","large","can"],name= 'unit')
df = pd.concat([Ingredients, Quantity, Unit], axis=1) #create new dataframe with column names
print(df)


0    Flour
1     Milk
2     Eggs
3     Spam
dtype: object
0    4
1    1
2    2
3    1
dtype: int64
0     cups
1      cup
2    large
3      can
dtype: object
       0  1      2
0  Flour  4   cups
1   Milk  1    cup
2   Eggs  2  large
3   Spam  1    can
  Ingredients  Quantity   unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [93]:
# Take this data and create a DataFrame named studentData
import pandas as pd

data = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }
studentData = pd.DataFrame(data)
print(studentData)


studentdata = pd.concat([Name, Height, Qualification, address, Age, Pets, sport], axis=1)
print(df)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket
      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [116]:
import pandas as pd
# Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
desserts = pd.Series(["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"])
studentData['desserts'] = desserts
print(studentData)
#Why is "Pdesserts" showing after I deleted?


      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

      Pdesserts      desserts  
3  Carrot Halwa  Carrot Halwa  
2       waffels       waffels  
0     ice cream     ice cream  
1  Cashew Fudge  Cashew Fudge  


In [104]:
# Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"
import numpy as np

studentData.sort_values(by = ['Name', 'address'], inplace = True)
print(studentData)


      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

      Pdesserts      desserts  
3  Carrot Halwa  Carrot Halwa  
2       waffels       waffels  
0     ice cream     ice cream  
1  Cashew Fudge  Cashew Fudge  


In [106]:
# Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:df.to_csv('cows_and_goats.csv', index=False)

studentData.to_csv('cows_and_goats.csv', index=False)

In [ ]:
# (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.